# Numpy

## import 하기

In [1]:
import numpy as np

## array 생성하기
- 중괄호 갯수 = 차원 수

In [3]:
array_1D = np.array([1,2,3])
print(array_1D)
print(array_1D.shape)

[1 2 3]
(3,)


In [4]:
array_2D = np.array([[1,2,3],
                     [4,5,6]])
print(array_2D)
print(array_2D.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
array_3D = np.array([[[1,2,3], 
                     [4,5,6],
                     [1,2,3],
                     [4,5,6]]])
print(array_3D)
print(array_3D.shape) # 1차원이 3개 들어간 3차원

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
(1, 4, 3)


In [6]:
array_3D = np.array([[[1,2,3], 
                     [4,5,6]],
                     [[1,2,3],
                     [4,5,6]]])
print(array_3D)
print(array_3D.shape) # 2차원이 2개 들어간 3차원

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


## 인덱싱하기

In [7]:
# array_2D : shape (2,3)
array_2D[0]

array([1, 2, 3])

In [8]:
array_2D[1]

array([4, 5, 6])

In [9]:
array_2D[1][1]

5

In [10]:
# array_3D : shape (2,2,3)
array_3D[0][1]

array([4, 5, 6])

## 기초 통계량 활용

In [11]:
array_1D.sum()

6

In [12]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array_2D.max()

6

In [14]:
array_2D.mean()

3.5

In [15]:
array_2D.min()

1

In [16]:
array_2D.sum()

21

## 모양 변경하기
- 보통은 pandas에서 많이 함.
- 딥러닝으로 넘어가고, tensorflow, PyTorch에 데이터를 넣어줄 때, 데이터 모양을 numpy로 reshape해서 넣어줘야 함.

In [18]:
array = np.arange(15)
print(array)
print(array.shape) # 15

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [24]:
reshape_array = array.reshape(3, 5)
print(reshape_array)
print(reshape_array.shape)
print(reshape_array.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
15


In [22]:
array.reshape(1,15) # 2차원으로 변경됨!

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [23]:
array.reshape(1,15).ndim

2

In [25]:
array.ndim

1

In [28]:
array_1D = np.arange(0, 100, 5)
print(array_1D)
print(array_1D.size)
print(array_1D.shape)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
20
(20,)


In [30]:
reshape_array_3D = array_1D.reshape(2,2,5)
reshape_array_3D

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

In [31]:
print(reshape_array_3D.size)
print(reshape_array_3D.shape)
print(reshape_array_3D.ndim)

20
(2, 2, 5)
3


## numpy array operation
- for문 돌리지 않아도 연산을 한꺼번에 할 수 있다.

In [32]:
data = [1,2,3]

In [33]:
data.sum()

AttributeError: 'list' object has no attribute 'sum'

In [ ]:
# numpy, scala 연산

In [34]:
np.array(data) * 10 # numpy array로 바꿔주면 한꺼번에 계산 가능

array([10, 20, 30])

In [ ]:
# numpy끼리 연산

In [35]:
array1 = np.array([[1,0],
                   [0,1]])
array2 = np.array([[1,2],
                   [3,4]])

In [36]:
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[[2 2]
 [3 5]]
[[ 0 -2]
 [-3 -3]]
[[1 0]
 [0 4]]
[[1.   0.  ]
 [0.   0.25]]


In [37]:
np.dot(array1, array2) # 행렬 곱 연산 > array1이 항등행렬이라서 값이 array2와 똑같이 나옴

array([[1, 2],
       [3, 4]])

## 다차원 연산

In [41]:
n3 = np.arange(1,13).reshape(3,4)
n3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
print(n3.std()) # 표준편차
print(n3.var()) # 분산
print(n3.cumsum()) # 누적합
print(n3.cumprod()) # 누적곱

3.452052529534663
11.916666666666666
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]


In [43]:
n3.sum()

78

In [ ]:
# 축의 방향

In [44]:
n3.sum(axis = 0) # column 방향으로 합 구함

array([15, 18, 21, 24])

In [45]:
n3.sum(axis = 1) # row 방향 합

array([10, 26, 42])

In [46]:
n3.max(axis = 0)

array([ 9, 10, 11, 12])

In [47]:
n3.max(axis = 1)

array([ 4,  8, 12])

In [48]:
n3.cumsum(axis = 0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]], dtype=int32)

In [49]:
n3.cumsum(axis = 1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]], dtype=int32)

## Stack

In [50]:
v1 = np.arange(11,16)
print(v1)

v2 = v1 + 10
v3 = v2 + 10
v4 = v3 + 10
print(v4)

[11 12 13 14 15]
[41 42 43 44 45]


In [52]:
vstack1 = np.vstack((v1,v2))
print(vstack1)
print('-' * 20)
vstack2 = np.vstack((v3,v4))
print(vstack2)
print('-' * 20)
v = np.vstack((v1,v2,v3,v4))
print(v)

[[11 12 13 14 15]
 [21 22 23 24 25]]
--------------------
[[31 32 33 34 35]
 [41 42 43 44 45]]
--------------------
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [53]:
print(v1.shape) # 1차원 (5,)
print(vstack1.shape) # 2차원 (2,5)
print(v.shape) # 2차원 (4,5) > 리스트 4개인데 5개 원소

(5,)
(2, 5)
(4, 5)


In [54]:
# 23을 선택하려면
v[1][2]

23

In [55]:
v[1,2]

23

In [60]:
# 슬라이싱

In [57]:
v[:,1]

array([12, 22, 32, 42])

In [58]:
v[1:3, 1]

array([22, 32])

In [59]:
v[1, :]

array([21, 22, 23, 24, 25])

### [실습]

In [62]:
v = np.array([[11, 12, 13, 14, 15],
              [21, 22, 23, 24, 25],
              [31, 32, 33, 34, 35],
              [41, 42, 43, 44, 45]])

In [63]:
# Q1. [33,34]

v[2,2:4]

array([33, 34])

In [66]:
v[2,[2,3]]

array([33, 34])

In [64]:
# Q2. [14,24, 34,44]
v[:,3]

array([14, 24, 34, 44])

In [65]:
# Q3. [[23,24],
#      [33,34]]
v[1:3,2:4]

array([[23, 24],
       [33, 34]])

## 조건연산
- **`매우 중요하다.`**
- 내가 원하는 데이터를 빠르게 가져올 수 있다.

In [67]:
# boolean 추출

In [68]:
arr = np.array([10, 20, 30])
arr > 10

array([False,  True,  True])

In [69]:
# 조건에서 True인 데이터들만 가져오기
arr[arr > 10]

array([20, 30])

In [70]:
arr[arr > 10 & arr < 30] # error > 괄호!

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [71]:
arr[(arr > 10) & (arr < 30)]

array([20])

In [72]:
arr[(arr > 10) and (arr < 30)] # error

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [73]:
condition = arr > 10
arr[condition]

array([20, 30])

In [74]:
# '~'은 반대
arr[~condition]

array([10])

In [75]:
# numpy의 where함수 > ex. 남녀 데이터 넣어주려면 숫자로 바꿔서 넣어줘야 함(0,1) 이때, where함수 or scikit-learn의 라벨 사용
arr2 = np.where(arr > 10, 1, 0) # True이면 1로, False이면 0으로 바꿔라
arr2

array([0, 1, 1])

In [76]:
arr3 = np.where(arr > 10, arr + 10, arr - 10) # True이면 +10, False이면 -10
arr3

array([ 0, 30, 40])